version: '3'

services:
  app:
    container_name: imagerhub-app
    restart: always
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    hostname: app
    ports:
      - ${APP_PORT}:3000
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  file:
    container_name: imagerhub-file-service
    restart: always
    build:
      context: .
      dockerfile: ./apps/file/Dockerfile
    hostname: file
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  db:
    image: mongo
    container_name: imagerhub-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend
    ports:
      - 27017:27017
networks:
  backend:
    driver: bridge